### PR TITLE
Nib files are available via CocoaPods

### PR DESCRIPTION
**Pull request by WataruSuzuki**
Hi,

I want to use Tutti via CocoaPods without merging nib files manually.
So I pull to request this changes.

Please check diffs😊 

Thanks

### CODE REVIEW

**Comment by danielsaidi** [comment]
Hi,

Thank you for the pull request! However, the xib files and image resources are intentionally placed in the example app and not in the library, since each app that uses Tutti will most probably use their own styles. Therefore, adding all images and xibs from the example project (which I haven't put that much time and energy into) would make all standard tutorials created with this library look sketchy.

However, I think you're on to something, that there should be some built-in styles, so that creating a basic tutorial becomes really easy. If so, I'll create an issue to add some nicer styles to it.

/Daniel

**Comment by WataruSuzuki** [comment]
Hi @danielsaidi 

Thank you for reviewing.
I modified my PR code by your response.

- Recommend as User's own style
  - Updated README
  - Updated samples 

Yes, I want to use as built-in style.
In my opinion, `TutorialViewController` is may not have a lot of customizability because it's can only  extend from `UICollectionViewController`.

It means change difficultly to other protocol even if User prepared User's own `.xib` file .
(Easy to customize size, color, text)

Or maybe implementation via `IBDesignable` and `IBInspectable` is better than this PR diffs.

**Comment by danielsaidi** [comment]
Hi again @WataruSuzuki 

I'm sorry for my very slow reply. I've been away traveling without my computer, and haven't had a chance to look at your changes.

I agree with the TutorialViewController - it should have a more specific name. I am currently busy with another library, but I will return to Tutti and improve things later, most probably in August.

I also want to wait with adding resources like xibs and images to the library, since I am planning to add support for Swift PM...and I don't think it supports static content. If so, I think that it would be better to add a bunch of tutorial styles that you can drag and drop from the demo app to your own app.

Would love to hear your thoughts on that idea.

**Comment by WataruSuzuki** [comment]
HI @danielsaidi 

Thank you for replying and sorry late to response.

I'm not mind supports static content or not.
And I'm not sure about "drag and drop" steps adding manuals. 
It means `Tutti` library cannot start without own Users customize.

I want to add the option : Can start without customize style.
- sometimes, I use `Tutti` with optimize own App.
- sometimes, I use `Tutti` ASIS (**default style)

Could you add `default/place holder` style for `Tutti`?

**Comment by danielsaidi** [comment]
Hi again @WataruSuzuki 

I will add improved tutorial support and some templates, when the new Xcode and iOS versions are released later this autumn. I hope to be able to get around to this in August/September.

**Pull request closed without merging**
